reviewers:
  # The default reviewers
  defaults:
    - maintainers

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    maintainers:
      - kgodey
      - mathemancer
      - pavish
      - seancolsen
    designers:
      - ghislaineguerin
    backend-reviewers:
      - kgodey
      - mathemancer
      - eito-fis
      - powellc
    frontend-reviewers:
      - pavish
      - seancolsen
      - dhruvkb
      - zackkrida

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    - maintainers
  'mathesar/**':
    - backend-reviewers
  'db/**':
    - backend-reviewers
  'mathesar_ui/**':
    - designers
    - frontend-reviewers

options:
  ignore_draft: true
  enable_group_assignment: false
