reviewers:
  # The default reviewers
  defaults:
    - engineers
    - designers

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    engineers:
      - kgodey
      - mathemancer
      - pavish
      - eito-fis
    designers:
      - ghislaineguerin
    frontend-reviewers:
      - dhruvkb
      - zackkrida

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    - engineers
    - designers
  'mathesar_ui/**':
    - frontend-reviewers

options:
  ignore_draft: true
  enable_group_assignment: false
