centerofci/mathesar-ansible:
  - .github/workflows/add-to-project.yml
  - .github/workflows/toc.yml
  - .github/workflows/stale.yml
  - .github/workflows/update-project-on-issue-assign.yml
  - .github/workflows/update-project-on-issue-close.yml
  - .github/workflows/update-project-on-issue-edit.yml
  - .github/workflows/update-project-on-issue-label.yml
  - .github/workflows/update-project-on-pr-edit.yml
  - .github/workflows/update-project-on-pr-label.yml
centerofci/mathesar-design:
  - .github/workflows/add-to-project.yml
  - .github/workflows/toc.yml
  - .github/workflows/stale.yml
  - .github/workflows/update-project-on-issue-assign.yml
  - .github/workflows/update-project-on-issue-close.yml
  - .github/workflows/update-project-on-issue-edit.yml
  - .github/workflows/update-project-on-issue-label.yml
  - .github/workflows/update-project-on-pr-edit.yml
  - .github/workflows/update-project-on-pr-label.yml
centerofci/mathesar-private-notes:
  - .github/workflows/add-to-project.yml
  - .github/workflows/toc.yml
  - .github/workflows/stale.yml
  - .github/workflows/update-project-on-issue-assign.yml
  - .github/workflows/update-project-on-issue-close.yml
  - .github/workflows/update-project-on-issue-edit.yml
  - .github/workflows/update-project-on-issue-label.yml
  - .github/workflows/update-project-on-pr-edit.yml
  - .github/workflows/update-project-on-pr-label.yml
centerofci/mathesar-scripts:
  - .github/workflows/add-to-project.yml
  - .github/workflows/toc.yml
  - .github/workflows/stale.yml
  - .github/workflows/update-project-on-issue-assign.yml
  - .github/workflows/update-project-on-issue-close.yml
  - .github/workflows/update-project-on-issue-edit.yml
  - .github/workflows/update-project-on-issue-label.yml
  - .github/workflows/update-project-on-pr-edit.yml
  - .github/workflows/update-project-on-pr-label.yml
centerofci/mathesar-wiki:
  - .github/workflows/add-to-project.yml
  - .github/workflows/toc.yml
  - .github/workflows/stale.yml
  - .github/workflows/update-project-on-issue-assign.yml
  - .github/workflows/update-project-on-issue-close.yml
  - .github/workflows/update-project-on-issue-edit.yml
  - .github/workflows/update-project-on-issue-label.yml
  - .github/workflows/update-project-on-pr-edit.yml
  - .github/workflows/update-project-on-pr-label.yml
