version: "3.9"

services:
  db:
    image: postgres:13
    container_name: mathesar_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB-mathesar_django}
      - POSTGRES_USER=${POSTGRES_USER-mathesar}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-mathesar}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  service-without-db:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: mathesar_service-w-db
    environment:
      - MODE=${MODE-PRODUCTION}
      - DJANGO_ALLOW_ASYNC_UNSAFE=true
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE-config.settings}
    command: ./run.sh
    ports:
      - "8000:8000"
      - "3000:3000"
      - "6006:6006"
  service:
    extends: service-without-db
    depends_on:
      - db
volumes:
  postgresql_data:
