version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB-mathesar_django}
      - POSTGRES_USER=${POSTGRES_USER-mathesar}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-mathesar}
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes:/var/lib/postgresql/data
  ui:
    build: ./mathesar_ui
    volumes:
      - ./mathesar_ui:/home/node/ui
      - /home/node/ui/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
  web:
    build: .
    command: dockerize -wait tcp://db:5432 -timeout 30s python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
