version: "3.9"

services:
  db:
    profiles: ["dev", "prod", "test"]
    image: postgres:13
    container_name: mathesar_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB-mathesar_django}
      - POSTGRES_USER=${POSTGRES_USER-mathesar}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-mathesar}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  service-without-db:
    profiles: ["web-server"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mathesar_service
    environment:
      - MODE=${MODE-PRODUCTION}
      - DEBUG=${DEBUG-False}
      - DJANGO_ALLOW_ASYNC_UNSAFE=true
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE-config.settings.production}
    command: ./run.sh
    ports:
      - "8000:8000"
  service:
    profiles: ["prod"]
    extends: service-without-db
    depends_on:
      - db
  test-service:
    profiles: [ "test" ]
    extends: service-without-db
    build:
      context: .
      # Replace with Dockerfile.integ-test when running integration tests
      dockerfile: Dockerfile
      args:
        PYTHON_REQUIREMENTS: requirements-dev.txt
    depends_on:
      - db
  dev-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_REQUIREMENTS: requirements-dev.txt
    profiles: ["dev"]
    extends: service-without-db
    environment:
      - MODE=${MODE-DEVELOPMENT}
      - DEBUG=${DEBUG-True}
      - DJANGO_ALLOW_ASYNC_UNSAFE=true
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/.Xauthority
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE-config.settings.development}
    command: dockerize -wait tcp://mathesar_db:5432 -timeout 30s ./dev-run.sh
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/.Xauthority
      - .:/code/
      - ui_node_modules:/code/mathesar_ui/node_modules/
    depends_on:
      - db
    ports:
      - "8000:8000"
      - "3000:3000"
      - "6006:6006"
volumes:
  postgresql_data:
  ui_node_modules: