version: "3.9"

services:
  db:
    image: postgres:13
    container_name: mathesar_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB-mathesar_django}
      - POSTGRES_USER=${POSTGRES_USER-mathesar}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-mathesar}
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  service:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: mathesar_service
    environment:
      - MODE=${MODE-PRODUCTION}
      - DJANGO_ALLOW_ASYNC_UNSAFE=true
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/.Xauthority
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE-config.settings}
    command: ./run.sh
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/.Xauthority
      - .:/code/
      - ui_node_modules:/code/mathesar_ui/node_modules/
    ports:
      - "8000:8000"
      - "3000:3000"
      - "6006:6006"
volumes:
  ui_node_modules:
