name: Find unused code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    # We only want to run on external PRs, since internal PRs are covered by "push"
    # This prevents this from running twice on internal PRs
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run Vulture
        uses: anaynayak/python-vulture-action@v1
        id: vulture
        with:
          vulture-args: ". --min-confidence 90"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
